### ISSUE TITLE
Fix null-pointer dereference in elastic proxy

### ISSUE THREAD

**Issue by mostafa** [gatewayd-io/gatewayd#338]
This is the traceback of what happens the connection count from clients grow more than the pool.

```bash
2023-09-27T22:47:13+02:00 DBG GatewayD is closing a connection from=127.0.0.1:52984
2023-09-27T22:47:13+02:00 ERR Failed to disconnect the server connection error="client is not connected"
2023-09-27T22:47:14+02:00 DBG GatewayD is opening a connection from=127.0.0.1:52986
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbcc7f7]

goroutine 153 [running]:
github.com/gatewayd-io/gatewayd/network.(*Client).IsConnected(0x0)
        /gatewayd/gatewayd/network/client.go:232 +0x557
github.com/gatewayd-io/gatewayd/network.(*Proxy).IsHealty(0xc0000ce8f0, 0x0)
        /gatewayd/gatewayd/network/proxy.go:469 +0x19a
github.com/gatewayd-io/gatewayd/network.(*Proxy).Connect(0xc0000ce8f0, {0x183a4c8?, 0xc0000fa700})
        /gatewayd/gatewayd/network/proxy.go:159 +0x408
github.com/gatewayd-io/gatewayd/network.(*Server).OnOpen(0xc00001b0e0, {0x183a4c8, 0xc0000fa700})
        /gatewayd/gatewayd/network/server.go:110 +0x403
github.com/panjf2000/gnet/v2.(*eventloop).open(0xc00040c780, 0xc0000fa700)
        /go1.21/global/pkg/mod/github.com/panjf2000/gnet/v2@v2.3.2/eventloop_unix.go:83 +0x3e
github.com/panjf2000/gnet/v2.(*eventloop).accept(0xc00040c780, 0x1?, 0x25?)
        /go1.21/global/pkg/mod/github.com/panjf2000/gnet/v2@v2.3.2/acceptor_unix.go:100 +0x3ec
github.com/panjf2000/gnet/v2.(*eventloop).run.func1(0xc0002b90e0?, 0x1)
        /go1.21/global/pkg/mod/github.com/panjf2000/gnet/v2@v2.3.2/reactor_default_linux.go:120 +0xcb
github.com/panjf2000/gnet/v2/internal/netpoll.(*Poller).Polling(0xc000335360, 0xc041727f38)
        /go1.21/global/pkg/mod/github.com/panjf2000/gnet/v2@v2.3.2/internal/netpoll/epoll_default_poller.go:138 +0x2b9
github.com/panjf2000/gnet/v2.(*eventloop).run(0xc00040c780)
        /go1.21/global/pkg/mod/github.com/panjf2000/gnet/v2@v2.3.2/reactor_default_linux.go:97 +0x94
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /go1.21/global/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 129
        /go1.21/global/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x96
exit status 2
```

**Comment by mostafa** [comment]
Elastic mode is going to be removed in #359.
